language: node_js
node_js: stable
# assign build branches
branches:
  only:
  - source

# cache this directory
cache:
  directories:
  - node_modules

git:
  submodules: false

before_install:
# Use sed to replace the SSH URL with the public URL, then initialize submodules
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - openssl aes-256-cbc -K $encrypted_8777397ac9a4_key -iv $encrypted_8777397ac9a4_iv -in ./.travis/id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/id_rsa
  - cp .travis/ssh_config ~/.ssh/config
  - npm install -g hexo-cli

install:
  - npm install

script:
  - hexo generate

after_success:
  - git config --global user.name "MeteoBoy4"
  - git config --global user.email "lichiqin4@gmail.com"
  - sed -i” “/^ *repo/s~github\.com~${githubToken}@github.com~” _config.yml
  - hexo deploy

# E: Build LifeCycle
